---

- name: Ensure version
  fail:
    msg: k9s_version is not specified, so it won't be installed
  when:
    - not k9s_version
  ignore_errors: yes
  tags:
    - k9s

- name: prepare directory
  become: yes
  file:
    path: '/opt/k9s-{{ k9s_version }}'
    state: directory
  when:
    - k9s_version
  tags:
    - k9s

- name: pull k9s release
  become: yes
  shell: 
    cmd: 'curl {{ k9s_release_tgz_url }} -L | tar -xz -C /opt/k9s-{{ k9s_version}}'
    creates: '/opt/k9s-{{ k9s_version}}/k9s'
  args:
    warn: no
  when:
    - k9s_version
  tags:
    - k9s

- name: update link
  become: yes
  file: 
    src: '/opt/k9s-{{ k9s_version }}/k9s'
    dest: '/usr/local/bin/k9s'
    state: link
  when:
    - k9s_version
  tags:
    - k9s
