---

- name: Provision workstation
  hosts: localhost
  gather_facts: yes

  vars_files:
    - ./vars/generic.yml

  roles:
    - common
    - user
    - role: git
      when: git_do_config
    - python
