---

- name: Provision workstation
  hosts: localhost
  gather_facts: yes

  vars_files:
    - ./vars/generic.yml

  roles:
    - common
    - user
    - role: git
      when: git_do_config
    - python
    - role: gcp
      when: gcp_do_install
    - docker
    - role: k9s
      when: k9s_do_install
