- name: change user shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - user

- name: install omz
  git:
    repo: '{{ omz_git_repository }}'
    dest: '{{ common_user_home }}/{{ omz_install_directory }}'
    update: true
    accept_hostkey: true
    version: 'master'
  tags:
    - user

- name: copy .zshrc to home dir
  ansible.builtin.template:
    src: .zshrc.j2
    dest: '{{ common_user_home }}/.zshrc'
  tags:
    - user
