---

- name: ensure apt list present
  become: yes
  lineinfile:
    state: present
    create: yes
    line: 'deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main'
    path: '/etc/apt/sources.list.d/google-cloud-sdk.list'
  tags:
    - gcp

- name: add key
  become: yes
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present
  register: gcp_apt_key_add
  tags:
    - gcp

- name: update apt
  become: yes
  ansible.builtin.apt:
    update_cache: yes
  when:
    - gcp_apt_key_add.changed
  tags:
    - gcp

- name: install gcp packages
  become: true
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - google-cloud-sdk-gke-gcloud-auth-plugin
    - google-cloud-cli
    - kubectl
  tags:
    - gcp

- name: register docker credential helpers
  command:
    cmd: 'gcloud auth configure-docker {{ item }} --quiet'
  with_items: '{{ gcp_configure_docker_registry }}'
  ignore_errors: yes
  tags:
    - gcp
