
- name: install pyenv
  git:
    repo: '{{ python_pyenv_repo }}'
    dest: '{{ common_user_home }}/{{ python_pyenv_dir }}'
    update: true
    accept_hostkey: true
    version: 'master'
  tags:
    - python

- name: configure pyenv
  ansible.builtin.blockinfile:
    path: '{{ common_user_home }}/.zshrc'
    insertbefore: 'source \$ZSH/oh-my-zsh.sh'
    block: |
      # Init pyenv just before omz being initalized
      # so that pyenv plugin could find pyenv distro
      export PYENV_ROOT="$HOME/{{ python_pyenv_dir }}"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    # append_newline: true
    # prepend_newline: true
  tags:
    - python

- name: install python versions
  command:
    cmd: '{{ common_user_home }}/{{ python_pyenv_dir }}/bin/pyenv install -s {{ item }}'
  with_items: '{{ python_versions }}'
  tags:
    - python