- name: Ensure git name and email set
  ansible.builtin.fail: msg="git name and email required"
  when:
    - git_name is undefined
      or git_email is undefined
      or not (git_email and git_name)
  tags:
    - git

- name: Set git name
  community.general.git_config:
    name: user.name
    value: '{{ git_name }}'
    scope: global
  tags:
    - git

- name: Set git email
  community.general.git_config:
    name: user.email
    value: '{{ git_email }}'
    scope: global
  tags:
    - git
