---

- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: username_on_the_host
  tags:
    - debug

- name: set a hostname
  become: true
  ansible.builtin.hostname:
    name: '{{ common_hostname }}'
  tags:
    - debug
  when: common_hostname

- name: Update apt cache
  become: true
  become_user: root
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: '{{ common_apt_cache_ttl }}'
  register: common_apt_update
  tags:
    - packages

- name: Install essential packages
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ common_apt_packages }}'
    state: latest
  tags:
    - packages

- name: Install extra packages
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ common_apt_packages_extra }}'
    state: latest
  tags:
    - packages

- name: Update all packages
  become: true
  become_user: root
  ansible.builtin.apt:
      name: '*'
      state: latest
  when:
    - common_apt_update.changed
  tags:
    - packages

- name: ensures .ssh conf dir exists
  file:
    path: '{{ common_user_home }}/.ssh'
    state: directory
  when:
    - common_user_ssh_do_config
  tags:
    - ssh

- name: Generate secret
  community.crypto.openssh_keypair:
    type: '{{ common_user_ssh_type}}'
    path: '{{ common_user_home }}/.ssh/id_{{ common_user_ssh_type }}'
  when:
    - common_user_ssh_do_config
  tags:
    - ssh
