k9s_do_install: no
k9s_version: ''
k9s_arch: 'amd64'
k9s_platform: 'Linux'
k9s_release_tgz: 'k9s_{{ k9s_platform }}_{{ k9s_arch }}.tar.gz'
k9s_release_tgz_url: 'https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/{{ k9s_release_tgz }}'
